In [1]:
import numpy as np

In [172]:
a = np.array([1,2,3,4,5] , dtype = np.int32)
b = np.array([[1,2],[3,4]])
c = np.array([[[1,2],[3,4],[5,6]]])

In [71]:
print(a)

[1 2 3 4 5]


In [72]:
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


**MAIN METHODS FOR MATRICES**

In [73]:
a = np.array([1,2,3,4,5] , dtype = float)
print(a)

[1. 2. 3. 4. 5.]


In [74]:
# np.arange
x = np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [75]:
y = np.arange(1,11,2)
print(y)

[1 3 5 7 9]


In [76]:
x.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [77]:
# Initializing a matrix 
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
np.random.random((5,4))

array([[0.24476673, 0.07751868, 0.52003218, 0.07068596],
       [0.94767125, 0.99887063, 0.46961668, 0.24510391],
       [0.17672854, 0.16821895, 0.22875229, 0.83436233],
       [0.45403754, 0.0227498 , 0.97851103, 0.12428785],
       [0.71904235, 0.23701313, 0.36929407, 0.02425476]])

In [80]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.linspace(-10,10,10 ,dtype = int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [82]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [83]:
# .ndim is used to find out the dimension of the matrix
c.ndim

3

In [84]:
# .shape is used to find the shape of the matrix

In [85]:
c.shape
"""As c is a 3-D array so the first number represents how many number of 2-D arrays
are there in the matrix and the rest two number gives the shape of those."""

'As c is a 3-D array so the first number represents how many number of 2-D arrays\nare there in the matrix and the rest two number gives the shape of those.'

In [86]:
print(a.size)
print(a)

5
[1. 2. 3. 4. 5.]


In [87]:

""" If u wanna find out the datatype of a vector or a matrix then u can use .itemsize that 
would give out the memory consumed by the each element in the matrix or vector. """
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

# You can .dtpe to find out the datatype of the matrix or vector

print(a.dtype)
print(b.dtype)

8
8
8
float64
int64


In [88]:
# CHANGING THE DATATYPES 
""" THE MAIN AIM OF CHANING THE DATATYPE OF A VARIABLE IS TO STORE THE DATA MORE EFFICIENTLY 
SUCH THAT THE SPACE EFFICIENCY CAN BE PRIORITIZED AND SAVE SPACE. """

In [95]:
print(a.dtype)

int32


In [104]:
a2 = a.astype('float')   """ The new variable has to be assigned the new data_type in order to save the changes """
print(a2.dtype)

float64


In [105]:
print(a.dtype)

int32


**ARRAY FUNCTIONS**

In [134]:
# max/min/product/sum
x = np.linspace(1,21 ,dtype = np.int32)
x = x.reshape(5,10)
print(x.sum())

526


In [135]:
np.max( x , axis = 0)

array([17, 17, 18, 18, 18, 19, 19, 20, 20, 21], dtype=int32)

In [145]:
z = np.arange(20).reshape(2,2,5)
print(z)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


****INDEXING AND SLICING****

In [144]:
print(z[0,1,1])
print(z[0,0,0])
print(z[1,0,0])
print(z[1,1,4])

6
0
10
19


In [149]:
s = np.arange(30).reshape(2,5,3)
print(s)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [150]:
s[0,1:3,0:2]
# Extracting the sub-portion of the matrix

array([[3, 4],
       [6, 7]])

In [152]:
s[1,3:5,1:3]

array([[25, 26],
       [28, 29]])

In [153]:
s[1,:,1]
# Extracting a particular column

array([16, 19, 22, 25, 28])

In [154]:
s[0,1,:]
# Extracting a particular row

array([3, 4, 5])

In [155]:
s[0,::2,::2]

array([[ 0,  2],
       [ 6,  8],
       [12, 14]])

In [168]:
s[1,1:4:2,::2]

array([[18, 20],
       [24, 26]])

In [180]:
a1 = np.arange(27).reshape(3,3,3)
print(a1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [176]:
a1[::2,0,::2 ]

array([[ 0,  2],
       [18, 20]])

In [178]:
for i in a1[0]:
    print(i , end = " ")

[0 1 2] [3 4 5] [6 7 8] 

In [182]:
for i in a1:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [183]:
# ACCESSING ALL THE ELEMENTS INDIVIDUALLY OF A MULTI-DIMENSIONAL MATRIX
for i in np.nditer(a1):
    print(i , end= " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [184]:
a1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [185]:
a1.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [193]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(3,4)
a4 = np.hstack((a2,a3))
a5 = np.vstack((a2,a3))
print(a4)
print(a5)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [195]:
np.hsplit(a4,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [199]:
np.hsplit(a4,8)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[12],
        [16],
        [20]]),
 array([[13],
        [17],
        [21]]),
 array([[14],
        [18],
        [22]]),
 array([[15],
        [19],
        [23]])]

In [200]:
np.vsplit(a5,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [201]:
np.vsplit(a5,6)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]