In [1]:
import numpy as np

In [11]:
a = [ i for i in range(10000000) ]
b = [ i for i in range(20000000 , 30000000) ]
c = []
import time
start = time.time()
for i in  range(len(a)):
    c.append(a[i] + b[i])
end = time.time()
t1 =  end - start
print(t1)

0.9428849220275879


In [12]:
a = np.arange(10000000)
b = np.arange(10000000 , 20000000)
start = time.time()
c = a + b 
end = time.time()
t2 =  end - start
print(t2)

0.10754776000976562


In [14]:
ratio = t1/t2
print(ratio)

8.767127478452098


**FANCY INDEXING**

In [26]:
a1 = np.arange(27).reshape(3,3,3)
print(a1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [30]:
a1[ [1],[1,2],[1]]
"""  |    |    |
     \/   \/   \/
   2-D   rows  columns
   array 
   
"""

array([13, 16])

In [38]:
z = np.random.randint(1,100,24).reshape(6,4)
print(z)

[[49 25 85  6]
 [85  8 48 59]
 [58 27 42 21]
 [13 11 80 50]
 [93 33 62 35]
 [22 38 65 86]]


**BOOLEAN INDEXING**

In [39]:
# find all numbers greter than 55
z[z>55]

array([85, 85, 59, 58, 80, 93, 62, 65, 86])

In [40]:
# find all numbers that are even
z[z%2 == 0]

array([ 6,  8, 48, 58, 42, 80, 50, 62, 22, 38, 86])

In [45]:
# find all numbers that are not divisible by 7 
z[z%7 != 0]
z[~(z%7 == 0)]

array([25, 85,  6, 85,  8, 48, 59, 58, 27, 13, 11, 80, 50, 93, 33, 62, 22,
       38, 65, 86])

In [44]:
# find all numbers that are even and greater that 25
z[ (z>25) & (z%2 == 0)]

array([48, 58, 42, 80, 50, 62, 38, 86])

******BROADCASTING******

In NumPy, broadcasting is a powerful mechanism that allows arithmetic operations to be performed on arrays of different shapes.
Normally, to add or multiply two matrices element-by-element, they need to be the exact same size. NumPy bypasses this restriction by virtually "stretching" or duplicating the smaller array across the larger array so they have compatible shapes—all without actually copying the data in memory (which keeps it blistering fast).

**The Rules of Broadcasting**:

When operating on two arrays, NumPy compares their shapes element-wise, starting from the trailing dimensions (from right to left).
Two dimensions are compatible only if:

                                                 They are equal
                                                       or
                                            One of them is exactly 1.

If neither condition is met, NumPy throws a ValueError: operands could not be broadcast together.
The Alignment Step: 
**If one array has fewer dimensions than the other, NumPy automatically prepends dimensions of size 1 to the left side of the smaller array's shape until both shapes have the same length**


In [49]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print('\n')
print(b)
print('\n')
print(a+b)

[[0 1 2]
 [3 4 5]]


[[ 6  7  8]
 [ 9 10 11]]


[[ 6  8 10]
 [12 14 16]]


In [50]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print('\n')
print(b)
print('\n')
print(a+b)

[[0 1 2]
 [3 4 5]]


[[0 1 2]]


[[0 2 4]
 [3 5 7]]


In [51]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print('\n')
print(b)
print('\n')
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[0 1 2]


[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [54]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print('\n')
print(b)
print('\n')
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[0 1 2]




ValueError: operands could not be broadcast together with shapes (3,4) (3,) 


THE ERROR RAISED is due to the fact that when the 1-D array would be expanded to 2-D in order
to get broadcasted by adding 1 on the head of smaller one  the numbers on the right hand side of
both the arrays would not be the same due to which the broadcasting will not be possible and the 
error would be raised!


In [57]:
a = np.arange(3).reshape(1,3) # (1,3) ---> (3,3)
b = np.arange(3).reshape(3,1) # (3,1) ---> (3,3)

print(a)
print('\n')
print(b)
print('\n')
print(a+b)

[[0 1 2]]


[[0]
 [1]
 [2]]


[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [58]:
a = np.array([1])
# shape -> (1,1) ---> (2,2) 
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print('\n')
print(b)
print('\n')
print(a+b)

[1]


[[0 1]
 [2 3]]


[[1 2]
 [3 4]]


In [60]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print('\n')
print(b)
print('\n')
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]




ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

The array dimension is matching but the shape is not.

In [61]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

**IMPORTANT EXAMPLE**

The first thought woukd be to check the dimension which is same for both but the shape is different 
so (2,2) -->  (4,4) but that would throw an error as modification can only  happen on [1] not on other numbers.

**BUILDING FXN**

In [63]:
# sigmoid
def sigmoid(array):
  return 1/(1 + np.exp(-(array)))


a = np.arange(100)

sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

**WORKING WITH EMPTY VALUES**

In [68]:
a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [66]:
a[~(np.isnan(a))]

array([1., 2., 3., 4., 6.])